### ISSUE TITLE
dita-ot-gradle does not use custom saxon jar

### ISSUE THREAD

**Issue by lionelmoi** [eerohele/dita-ot-gradle#10]
In order to use Xpath math functions (https://www.w3.org/2005/xpath-functions/math/) I added Saxon 9.6 PE to the OT through the ... extension point.

It works when I launch a transformation through the dita command but it throws an exception with dita-ot-gradle : 

> Cannot a matching 1-argument function named {http://www.w3.org/2005/xpath-functions/math}exp()

Which means it's using the Saxon 9.1 bundled in the OT.

Do you have an idea?

**Comment by eerohele** [comment]
The first thing I would probably advise you to try is to add Saxon-PE into the Gradle classpath as well (in the buildscript block, see https://github.com/eerohele/saxon-gradle/issues/3).

However, you'll probably encounter the same issue with the Saxon license as you did with the saxon-gradle plugin. I'll try to look into that.

**Comment by eerohele** [comment]
One option might be to add a property that defines path(s) to add into the DITA-OT classpath before the default paths.

Something like:

```groovy
classpath = ['/path/to/Saxon-PE.jar']

ditaOt.dir ...

dita {
  ...
}
```

**Comment by eerohele** [comment]
https://github.com/eerohele/dita-ot-gradle/commit/96c86f4eddc7767792cd6f7c2be7ebff1605a841 has an initial implementation.

I'll take another look tomorrow with fresh eyes and if everything looks OK, I'll deploy a new version.

Sorry it took so long. Hope you still have use for the feature. :)

**Comment by eerohele** [comment]
Cut 0.5.0, which introduces the `classpath` option on the `ditaOt` task that lets you override or augment the DITA-OT classpath.

In your case, this should do the trick:

```groovy
ditaOt {
    dir '/path/to/dita-ot'

    classpath getDefaultClasspath(project).matching {
        exclude('**/saxon*.jar')
    } + file('saxon9pe.jar')
}
```

I'm going to close this issue, but if you experience any problems with it, please feel free to comment here or open a new issue.
