### ISSUE TITLE
FATAL error with 0.5.0

### ISSUE THREAD

**Issue by lionelmoi** [eerohele/dita-ot-gradle#15]
Following issue https://github.com/eerohele/dita-ot-gradle/issues/10 I used the `0.5.0` version and got an error during the copy-phase.

`[ant:branch-filter] Failed to parse file:/C:/temp/dita-transform/build/tmp/L2_help_whats_new_publi.ditamap`

It seems all ditamaps are renamed with a generated suffix : `L2_help_illus.ditamap.tmp1512028981408`

I attached the source map, the tmp dir and the stacktrace.

[L2_help_whats_new_publi.zip](https://github.com/eerohele/dita-ot-gradle/files/1516946/L2_help_whats_new_publi.zip)
[tmp.zip](https://github.com/eerohele/dita-ot-gradle/files/1516947/tmp.zip)
[stacktrace.log](https://github.com/eerohele/dita-ot-gradle/files/1516938/stacktrace.log)

`build.gradle`

```
plugins {
    id 'com.github.eerohele.dita-ot-gradle' version '0.5.0'
}



ditaOt{
	ditaOt.dir 'c:/DITA-OT'
	classpath  getDefaultClasspath(project).matching {
		exclude('**/saxon*.jar')
	} + file('c:/saxon/saxon9ee.jar')
}


dita{
	dependsOn "ditaOt"
	input "c:/workspace/L2-head/L2_optimization_TB_publi.ditamap"
	output "build/out"
	temp "build/tmp"
	transtype "pdf"
}
```

**Comment by lionelmoi** [comment]
It seems it is linked to the saxon version I'm using...

**Comment by eerohele** [comment]
I'll look into it when I get the chance, but are you able to test whether this problem occurs if you run DITA-OT directly (as in, without this plugin) with that particular Saxon version? 

IIRC, a quick-and-dirty way to check would be to move the Saxon JAR that comes bundled with DITA-OT out of the `lib` directory temporarily and drop `saxon9ee.jar` and the license file in there.

**Comment by lionelmoi** [comment]
Yep that was related to the Saxon-EE version. I removed the dependency and it works now.

**Comment by eerohele** [comment]
Which dependency did you remove?

What do you mean by "it works now"? Do you mean that you're able to use Saxon-PE/EE with the DITA-OT Gradle Plugin?

**Comment by lionelmoi** [comment]
I removed the Saxon-EE dependency from my plugin. I use a solution provided by the `org.dita-community.i18n` plugin.

To sum up my findings more clearly:

- dita-ot-gradle 0.5.0 imports the saxonee.jar in the classpath
- saxonEE 7.2 breaks the build (I have to buy new licenses to test with saxonEE 8.x)

**Comment by lionelmoi** [comment]
I tried it again with saxonHE 9.7 (I don't need EE to use the math extension) and it works like a charm.

**Comment by eerohele** [comment]
I'll close this one, too. Feel free to open a new issue if necessary.
