### ISSUE TITLE
Specify contributor requirements

### ISSUE THREAD

**Issue by sanderson-sfdc** [eerohele/dita-ot-gradle#17]
Are you open to pull requests?  If so, if I submit a pull request, do you require a contributor license agreement, a developer certificate of origin (like the DITA-OT), or something else?

**Comment by eerohele** [comment]
>Are you open to pull requests?

Certainly! PRs are very welcome.

>If so, if I submit a pull request, do you require a contributor license agreement, a developer certificate of origin (like the DITA-OT), or something else?

I don't require anything like that. Honestly, I haven't given that much thought.

I'll look into adding a `CONTRIBUTING.md` file. In the meantime, all PRs are very welcome.

**Comment by sanderson-sfdc** [comment]
Thanks; it would be helpful, I think, to match up with what the DITA-OT requires, just so that if, in the future, you want to merge your work with theirs, it's easy to do.

**Comment by eerohele** [comment]
>if, in the future, you want to merge your work with theirs, it's easy to do.

That's very unlikely.

I believe the "official" solution for the kind of problem this plugin tries to solve is [Kuhnuri](https://github.com/kuhnuri).

It doesn't offer a direct Gradle integration, but it should be possible to build a Gradle layer on top if Kuhnuri if necessary. From what I understand, Kuhnuri aims to provide a much more complete (open source) DITA publishing solution.

**Comment by sanderson-sfdc** [comment]
Fair enough.  It just seems like a natural thing to have similar checkin requirements to make it easy for people working in related areas.

**Comment by eerohele** [comment]
I don't feel that a `CONTRIBUTING.md` file is really necessary for this project at this point. All contributions are most welcome, and if you want to make a pull request, just make it and we'll walk through the process together.

We can revisit this decision later in the exceedingly unlikely event that the number of contributions increases.
