### ISSUE TITLE
Allow setting DITA-OT location in execution phase

### ISSUE THREAD

**Issue by eerohele** [eerohele/dita-ot-gradle#19]
- [x] Add `ditaOt` property to `dita` task
- [x] Add support for custom classpath definitions
- [x] Add unit tests
- [x] Add support for automatic plugin installation in execution phase
- [x] Write documentation
- [x] Add examples
- [x] Investigate automatic DITA-OT download either via GitHub releases or by cloning a Git tag

**Comment by eerohele** [comment]
I have an initial cut of code that lets you do this:

```groovy
dita {
    ...
    plugins 'org.lwdita': 'https://github.com/jelovirt/org.lwdita/releases/download/2.0.5/org.lwdita-2.0.5.zip'
    ...
}
```

The plugins listed under `plugins` are installed in the execution phase. The `plugins` property takes a map of DITA-OT plugin ID to plugin installation file system path or URL.

The plugin ID (the map key) is cross-referenced against `$DITA_HOME/config/plugins.xml` to check whether the plugin is already installed. If there's a plugin with that ID, it won't be installed again.

I now realize that the problem with this approach is that the plugin will also be left uninstalled even if the plugin version changes. The problem is that the DITA-OT `plugin.xml` format doesn't require the user to define the plugin version, so we can't cross-check against that.

Need to think on this more. It's not a trivial problem, in any case. I can't write a full-fledged dependency management system around this plugin, either...

**Comment by lionelmoi** [comment]
I'm having trouble with the classpath definition (following the solution introduced in https://github.com/eerohele/dita-ot-gradle/issues/10).

Could I define the ditaOt classpath in the dita task?

In my context I'm creating several tasks with `type: DitaOtTask` each whith its own ditaOt.dir.

**Comment by eerohele** [comment]
I haven't yet thought about how custom classpath definitions relate to this change. I'll need to look into it.

**Comment by eerohele** [comment]
I've now gotten custom classpath definitions to work in my local version, too. I'll need to clean things up quite a bit before I can cut another beta release, but at least things are slowly progressing.

One concern I have is that I won't be able to retain full backwards compatibility. I really don't like that, but I'm not sure it can be avoided at this point. My initial decision to define the DITA-OT directory in the configuration phase was a poor one, unfortunately.

**Comment by eerohele** [comment]
I've also decided to move the documentation for this plugin from the DITA files into the README file in this repo.

I realize it's a bit ironic, but honestly, updating the documentation is currently too much of a pain. For documentation this lightweight, I have much better chance of keeping it up to date if I just go with a plain old README file.

**Comment by fviolette** [comment]
Makes sense... though the output was nice.
To add insult to injury, should the doc/examples develop further, there's always Jekyll or Antora to save the day.

**Comment by eerohele** [comment]
Regarding plugin management: I just spoke briefly with Jarno about the upcoming DITA-OT plugin registry in DITA-OT v3.2, and it sounds like it's a much better idea to let DITA-OT handle plugin installation rather than teaching this plugin to do it.

It's not yet clear whether there'll be a `package.json` type dependency manifest that specifies which plugins to install, but if so, we could just add an option that points to that file and let DITA-OT handle plugin installation.

Either way, I think won't be spending more effort into that part of this change. I'll continue with custom classpath definitions when I get time.

**Comment by lionelmoi** [comment]
I'm good with that, I handle plugin dependency in my build, I would not want the plugin to do it 

:+1: for custom classpath definition

**Comment by eerohele** [comment]
Sorry this is taking so long — I'm having a bit of trouble finding the time to complete the work in my current life situation. I just wanted to say that I do intend to get this done, hopefully during this year.

**Comment by eerohele** [comment]
I released 0.6.0-beta2, which adds support for custom classpath definitions.

Here's an example of how you do it:

```gradle
dita {
    ditaOt '/path/to/dita-ot'
    input 'dita/root.ditamap'
    transtype 'html5'

    classpath defaultClasspath.matching {
        exclude('**/Saxon-HE*.jar')
    } + file('saxon-pe.jar')
}
```

@lionelmoi When you have the time, could you give it a try and see if it works for you?

I've tried hard to retain backwards compatibility, so the new version shouldn't break any existing builds. If it does, please let me know and I'll look into it.

**Comment by lionelmoi** [comment]
Thanks for the update.

When I switch to the beta2 without adding the classpath clause I get this message:
```
The "ditaOt" task is deprecated. Use dita { ... ditaOt "/path/to/dita-ot" ... } instead.
```

When I add the classpath clause I get this message:
```
I use the `DitaOtTask` declaration: `task "dita.${docType}" (type: DitaOtTask){` since I generate ditaOt tasks in a loop.

A problem occurred evaluating root project 'doc-manual'.
> You must specify the DITA-OT directory (ditaOt.dir) before you can retrieve the plugin classpath.
```
So it seems I cannot define the dita-ot dir at execution time anymore. :-/

**Comment by eerohele** [comment]
Thanks for trying it out. I’ll look into it.

**Comment by eerohele** [comment]
I can't reproduce that issue (except the first deprecation message, which is expected). To reiterate, your task should look something like this:

```groovy
...

// Remove the ditaOt { dir } bit.

...

task "dita.${docType}" (type: DitaOtTask) {
   ditaOt '/path/to/dita-ot'
   input '...'

   classpath defaultClasspath.matching {
        exclude('**/Saxon-HE*.jar')
    } + file('saxon-pe.jar')
}

...
```

If your task already looks like that, the issue must be related to something else (possibly the loop in your buildfile), in which case I need to take another look.

**Comment by eerohele** [comment]
@lionelmoi Can you confirm whether your task looks something like the one in my previous comment?

If it does and you still get that same error, I'll look into it.

**Comment by infotexture** [comment]
@eerohele Tested latest `0.6.0-beta1` release w/ dita-ot/docs@85dc6ef, builds successfully. ✅

**Comment by lionelmoi** [comment]
@eerohele a little bit late to the party but I will not be able to test this one. I changed company and I lost access to the environment...

Sorry about that.

**Comment by eerohele** [comment]
@lionelmoi No worries!

I'll proceed with this change in any case when I get the chance.

I think I'll try rewiring the internals of the plugin to use the [Gradle Worker API](https://guides.gradle.org/using-the-worker-api/) while I'm at it. That way we can remove the dependency to some of Gradle's internal classes I had to use before the Worker API became available.

**Comment by infotexture** [comment]
> I think I'll try rewiring the internals of the plugin to use the Gradle Worker API while I'm at it.

👍 Sounds like a good idea if it's not too much extra work.

**Comment by eerohele** [comment]
>>I think I'll try rewiring the internals of the plugin to use the Gradle Worker API while I'm at it.

>👍 Sounds like a good idea if it's not too much extra work.

This didn't pan out because as far as I can tell, the Worker API is not compatible with the way Gradle executes Ant.

However, I was able to [significantly reduce the amount of code that relies on Gradle internals](https://github.com/eerohele/dita-ot-gradle/commit/10f275da8626dc22b7a1566f239a509d736d7dfa).

I've released **0.6.0-beta5**, which includes these changes. @infotexture: if you have the time, could you give **0.6.0-beta5** a spin with the DITA-OT docs build and let me know whether everything looks OK (and whether there seems to be any regression with regard to performance)?

If everything works OK, I think the only thing blocking a 0.6.0 release is that the tests for the plugin fail on Windows for some reason.

**Comment by eerohele** [comment]
All right, I think I've squashed every CI bug I have the energy to tackle right now, so we're almost go for 0.6.0.

**Comment by infotexture** [comment]
@eerohele ✅ Docs builds run fine with the new version _(results are identical)_. 

Build durations seem reasonable:

- 2m 11s for builds with previous plug-in version 0.5.0
- 3m 1s for first build with 0.6.0-beta5 _(including fetching new plug-in version)_
- 2m 20s for subsequent build with 0.6.0-beta5

**Comment by eerohele** [comment]
@infotexture: Many thanks for giving it a go!

I'll tie up some loose ends and release 0.6.0 soon.

**Comment by eerohele** [comment]
0.6.0 released. See the buildfile [`download`](https://github.com/eerohele/dita-ot-gradle/blob/master/examples/download/build.gradle) example for details.
