### ISSUE TITLE
dita task "properties" are relative to the build script called (Multi-Project builds)

### ISSUE THREAD

**Issue by fviolette** [eerohele/dita-ot-gradle#20]
Base structure will be the [multi build example](https://github.com/eerohele/dita-ot-gradle/tree/master/examples/multi).

If I place `docs.min.css` under `one/css`, and add the following `one.properties` file under the `one` directory next to `one.ditamap`:

```
args.copycss = yes
args.css = docs.min.css
args.cssroot = css
args.csspath = css
```

... building the root project with `gradle` or using `gradle :one:dita` is not going to copy the CSS file along with the output.

And vice versa – if I put the CSS file under the `css` dir at the root project level (not desirable IMHO...), then I cannot run `gradle` from the `one` directory and get the CSS copied.

Thanks for your help.

**Comment by fviolette** [comment]
This issue occurred as I set up a multi-project buildin a nested folder and needed to refer to files above. I eventually managed by copying the css via a dedicated task, among other things. A similar pain point was setting args.xsl in a property file, even with ${projectDir} or ${rootDir}.

Could be closed.

**Comment by infotexture** [comment]
> building the root project with `gradle` or using `gradle :one:dita` is not going to copy the CSS file along with the output.

@fviolette This may be related to https://github.com/dita-ot/dita-ot/issues/3016.

**Comment by fviolette** [comment]
Issue solved AFAIC with `args.fo.userconfig = ${projectDir}/<uplevel-to-my-fop-xconf-file>` for instance.
