### ISSUE TITLE
support open toolkit 3.3 with LightWeightDita

### ISSUE THREAD

**Issue by friej1** [eerohele/dita-ot-gradle#21]
Do you have any plans to support open toolkit 3.3, and therefore LwDITA?

**Comment by infotexture** [comment]
What sort of support are you looking for?

We use the DITA-OT Gradle Plugin to publish the documentation for the toolkit itself, and it works fine with DITA-OT 3.3.1 and LwDITA source files.

**Comment by friej1** [comment]
We would like to use it for internal docs using MDita. From what you say, that is already possible. I’m new to the DITA world, and it seemed like the plugin used an earlier version of DITA and might not work with LwDita. This is good news.

**Comment by eerohele** [comment]
(Sorry for the delay, GitHub email notifications have landed in my spam folder for a while for some reason...)

Yeah, I'm not aware of any issues that would prevent you from using DITA-OT 3.3 & LwDITA. All I can say is give it a go and if you come across any issues, let me know and I'll look into it.

**Comment by infotexture** [comment]
The DITA-OT Gradle Plugin doesn't bundle the DITA Open Toolkit itself, it just makes it easier to use DITA-OT with Gradle.

You'll need to install DITA-OT separately per https://www.dita-ot.org/dev/topics/installing-client.html and set up a Gradle script per https://eerohele.github.io/dita-ot-gradle/#ariaid-title3, but the latest versions of both should work fine with MDITA content.

**Comment by friej1** [comment]
Right. Thanks.

**Comment by eerohele** [comment]
I'll close this issue, but if you come across any problems with using this plugin with DITA-OT 3.3+ and LwDITA, please feel free to comment here or open a new issue.
