### ISSUE TITLE
DITA_HOME is not used

### ISSUE THREAD

**Issue by stefan-jung** [eerohele/dita-ot-gradle#3]
The [build file of the examples/simple](https://github.com/eerohele/dita-ot-gradle/blob/develop/examples/simple/build.gradle#L14) says:

> // By default, it will use your DITA_HOME system environment variable.

But if it is missing, the following message appears:

> DITA Open Toolkit directory not set. Add a line like this into build.gradle

Could you please remove the comment or use to the environment variable?

**Comment by eerohele** [comment]
Thanks for reporting the issue!

Yeah, an early iteration of the plugin used `DITA_HOME`, but I removed that functionality. IIRC, DITA-OT uses `DITA_HOME` for some things and having it set can cause weird issues that are difficult to debug, so I wanted to avoid that. Might've been other reasons, too — don't remember off the top of my head.

**Comment by stefan-jung** [comment]
Thank you for coding this plugin. ;)

**Comment by stefan-jung** [comment]
If you plan to implement this again one time, you might want to check out the following thread to set the variable, if it is not defined: [Define a variable and set it to a default value if something goes wrong during definition](http://stackoverflow.com/questions/21104401/define-a-variable-and-set-it-to-a-default-value-if-something-goes-wrong-during-d)
