### ISSUE TITLE
input path doesn't work with "special" characters in it

### ISSUE THREAD

**Issue by sanderson-sfdc** [eerohele/dita-ot-gradle#7]
The dita ot developer archive uses a path like this:  dita-ot-2.3+45e1331

That works fine for the ditaOt.dir property, but not in the input param.

I'm on a Mac running El Capitan, with bash as my shell.

Test case:
1. In ~/dita unzip the latest dita-ot developer archive.  Notice it creates a directory like dita-ot-2.3+45e1331
2. In ~/dita, create a new directory "gradle-test"
3. Copy the attached build.gradle file into gradle-test
4. In gradle-test, run gradle

Resulting error message (replaced my path with /.../ for ease of reading):

radle
:dita FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dita'.
  
  > The following error occurred while executing this line:
  > /.../dita-ot-2.3+45e1331/build.xml:41: The following error occurred while executing this line:
  > /.../dita-ot-2.3+45e1331/plugins/org.dita.base/build_preprocess.xml:42: Failed to run pipeline: [DOTA069F][FATAL] Input file 'file:/.../dita-ot-2.3+45e1331/docsrc/userguide.ditamap' cannot be located or read. Ensure that file was specified properly and that you have permission to access it.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.945 secs

[build.gradle.zip](https://github.com/eerohele/dita-ot-gradle/files/312884/build.gradle.zip)

**Comment by eerohele** [comment]
Thanks for the report!

This seems to be a bug in DITA-OT itself rather than this plugin. I created https://github.com/dita-ot/dita-ot/issues/2414 — you can follow the progress there.
