### ISSUE TITLE
run plugin installation from gradle

### ISSUE THREAD

**Issue by lionelmoi** [eerohele/dita-ot-gradle#8]
Hi !

I would like to run the -install command from gradle, so far I have doen through the exec method, which is fine, but I wonder if you implemented the method in your plugin. 

Thanks again for all your work !

**Comment by eerohele** [comment]
So you mean something like this?

``` groovy
ditaOt.dir '/opt/dita-ot'

install {
    plugins 'https://foo.com/dita-ot-plugin-1.zip', '/my/plugins/dita-ot-plugin-2.zip'
}
```

And then when you run the `install` task, it would install the plugins into the DITA-OT installation you define via `ditaOt.dir`? If so, that shouldn't be too difficult.

I was wondering, though, would it be useful for you to also be able to do something like this?

``` groovy
ditaOt.dir '/opt/dita-ot'

install {
    version '2.3.1'
    plugins 'https://foo.com/dita-ot-plugin-1.zip', '/my/plugins/dita-ot-plugin-2.zip'
}
```

The plugin would then download DITA-OT 2.3.1 from GitHub, install it into `ditaOt.dir` and then install the plugins on top of that DITA-OT installation? That would be a bit more work, but it might be a nice feature.

**Comment by eerohele** [comment]
Well, I ended up with this syntax:

``` groovy
ditaOt {
    // Tell Gradle where your DITA-OT installation is.
    dir '/opt/dita-ot'

    // Optionally, give Gradle a list of DITA-OT plugins to install. To install
    // them, run:
    //
    // $ gradle ditaOt
    plugins 'https://github.com/dita-ot/org.dita.normalize/archive/1.0.zip'
}
```

I also deployed version 0.4.0 of the plugin with support for installing plugins. You can install multiple plugins by doing something like:

``` groovy
    plugins 'my-awesome-plugin-1.zip', 'my-awesome-plugin-2.zip'
```

@lionelmoi: Can you please give it a go and let me know whether it works for you?

Regarding installing DITA-OT itself automatically, I came to the conclusion that it's not really viable to install DITA-OT and run it immediately afterwards in a single execution when the Gradle Daemon is enabled, so I had to abandon that plan at least for now.

**Comment by lionelmoi** [comment]
Hi !

You work fast :)

I tried it and it does not seem to install any plugins in my dita-ot/plugins folder.

I put ditaOt task in another task as such : 

```
task installPlugins{
    dependsOn "extractDeps"
    ditaOt {
        dir extractRoot + "ditaot"
        plugins pluginurl
    }
}
```

and ran it prior to my main dita task. I get not error message either.

I liked the idea of a separate **install{}** task, this way it would be easier to differentiate between transformation and installation which are two separate steps.

As far as installation of the DITA-OT plugin from github, I have stored the dita-ot zip on an Artifactory server and define it as a dependency. So I would mind getting it from the actual source.

As far as continuous build is concerned I do not think it is an issue, I would have a separate conditional build running only if the toolkit is not installed or not up to date.

Hope that helps !

**Comment by eerohele** [comment]
> I put ditaOt task in another task as such :
> 
> ``` groovy
> task installPlugins{
>    dependsOn "extractDeps"
>    ditaOt {
>        dir extractRoot + "ditaot"
>        plugins pluginurl
>    }
> }
> ```

That won't work — `ditaOt` is already a task.

Try this instead:

``` groovy
ditaOt {
    dependsOn "extractDeps"
    dir extractRoot + "ditaot"
    plugins pluginurl
}
```

**Comment by lionelmoi** [comment]
Hi,

It works !
Only caveat is I cannot uninstall plugins. Which can be fine as long as I re-install the toolikt every time.

One other thing. Can I create a task that has another name? Using a syntax like :

> task taskName (Type:ditaOt) 

Cheers.

**Comment by eerohele** [comment]
> Only caveat is I cannot uninstall plugins.

Hmm… I'll need to think about that a bit.

> One other thing. Can I create a task that has another name?

Yes, see "Versatile publishing" at https://eerohele.github.io/dita-ot-gradle.

**Comment by lionelmoi** [comment]
I'm trying to feed a list to the plugin parameter:

```
def pluginList = ['../plugins/base-1.0.zip','../plugins/pagebreak-1.0.zip','../plugins/pdf-1.0.zip','../plugins/noprint-1.0.zip','../plugins/covers-1.0.zip','../plugins/break-1.0.zip','../plugins/um-1.0.zip']

ditaOt{
	dependsOn 'extractPlugins'
	dir 'ditaOt'
	plugins pluginList
}
```

and I'm getting the following message 

```
> The following error occurred while executing this line:
  C:\workspace\RDDOC_technical_documentation\gradle\transform\build\subprojects\build\ditaotUM\integrator.xml:103: java.net.MalformedURLException: no protocol: [../plugins/base-1.0.zip, ../plugins/pagebreak-1.0.zip, ../plugins/pdf-1.0.zip, ../plugins/noprint-1.0.zip, ../plugins/covers-1.0.zip, ../plugins/break-1.0.zip, ../plugins/um-1.0.zip]
```

It seems the DitaOtSetuptask is not iterating on the content of the `plugins` parameter as it should : 

[DitaOtSetupTask.groovy : line 27](https://github.com/eerohele/dita-ot-gradle/blob/1560f31d7be1d45eb623a0e5e1e2411f5dbf9b61/src/main/groovy/com/github/eerohele/DitaOtSetupTask.groovy)

```
        AntBuilderAssistant.getAntBuilder(project).execute {
            this.plugins.each { Object plugin ->
                ant(
                    antfile: new File(this.dir, 'integrator.xml'),
                    target: 'install',
                    useNativeBaseDir: true
                ) {
                    property(name: 'plugin.file', value: plugin.toString())
                }
            }
        }
```

It works when I give him the list directly:

```
ditaOt{
	dependsOn 'extractPlugins'
	dir dirDitaOt.toURI()
	/*plugins paths.join(',')*/
	plugins '../plugins/base-1.0.zip','../plugins/pagebreak-1.0.zip','../plugins/pdf-1.0.zip','../plugins/noprint-1.0.zip','../plugins/covers-1.0.zip','../plugins/break-1.0.zip','../plugins/um-1.0.zip'

}
```


Do you have an idea?

**Comment by eerohele** [comment]
Sorry for not getting back to you sooner -- I had completely missed your latest comment.

I haven't tried, but I think `plugins *pluginList` (aka the Groovy splat operator) should work. Can you give that a try?

**Comment by lionelmoi** [comment]
It does not throw an error any more but no plugin in copied into the dita-ot `plugins` directory...

**Comment by eerohele** [comment]
Weird. `plugins(*myPlugins)` seems to work OK for me. (The parentheses turned out to be necessary, which you probably already noticed.)

What command(s) are you using to invoke Gradle?

**Comment by lionelmoi** [comment]
It works !

I was using `plugins *.pluginList` but with `plugins(*pluginList)` it works like a charm.

**Comment by eerohele** [comment]
Good to hear. Sorry about the inaccurate advice -- haven't done Groovy in a while and the syntax is a bit funky...

**Comment by lionelmoi** [comment]
I'd even go as far as saying it is a total mess :)

**Comment by eerohele** [comment]
I think we can close this one.
